### ISSUE TITLE
Bonjour !

### ISSUE THREAD

**Issue by Baptiste-Garcin** [Behel/mpg-scrapper#1]
Je voulais savoir… Est-ce que vous savez comment on peut report un projet ?

Merci beaucoup de votre aide !

E-Cordialement

**Comment by Behel** [comment]
Je suppose que c'est ici : https://github.com/contact 

Mais plutôt que de report le projet, autant me demander gentillement de le supprimer et pourquoi je l'ai créé non ? C'est une pratique plutôt cordiale et vous en saurez un peu plus comment les gens jouent à MPG ;)
