### ISSUE TITLE
Can't have the Token ...

### ISSUE THREAD

**Issue by jak-dev** [Behel/mpg-scrapper#3]
Merci pour ce projet. Est il encore possible de l'utiliser sur mpg? Apres plusieurs tentative je n'arrive pas a me connecter.

E-cordialement :)

**Comment by Behel** [comment]
Etrange, ca marche toujours bien chez moi. Où se situe l'erreur ?

**Comment by jak-dev** [comment]
token = data_scrapper.get_token(username, pwd)
return
NoTokenException("Can't have the Token ...")
Est ce un probleme d'identifiant ou de nom de ligue?

**Comment by Behel** [comment]
Désolé de ne pas avoir répondu plus tôt

A mon avis il s'agit d'un problème avec le mot de passe ou l'adresse mail de ton côté, ce message d'erreur est retourné dans ce cas là notamment (il faudrait que je le rende plus explicite ^^')
