### ISSUE TITLE
League MPG

### ISSUE THREAD

**Issue by Zaelarom** [Behel/mpg-scrapper#4]
Bonjour,

Merci pour ce script !

Néanmoins, je n'arrive pas à récupérer les infos car j'ai le message d'erreur suivant : "NoLeagueException: "The league X doesn't exists".
Par league il faut mettre quoi exactement ? Le code d'une de nos ligues en cours ?

Merci ! :)

**Comment by Behel** [comment]
Oui, il faut mettre dans idents.ini le code de la ligue (celui présent dans l'URL sur MPG) :)
